apiVersion: v1
kind: Secret
metadata:
    name: thermo-api-secret
    namespace: thermo
type: Opaque
stringData:
    db_password: ENC[AES256_GCM,data:qt4kgybVNUMghg==,iv:zUu4tP3KWlFbXVm/LHn64N4m5LiH4d1kVSbGPNs946g=,tag:SdFejhSh+DEOxo+EzMcrKg==,type:str]
    api_token: ENC[AES256_GCM,data:0gCVln4ta6q7duVn4hlfeJ7cpng=,iv:0bB7TugFFXxjuAf2uyHjnvZt6F96RYYZjA+IlvlQYGY=,tag:oMPjLAGt1o03KjaidT04YQ==,type:str]
sops:
    age:
        - recipient: age17mu4gj9g8yjl68s9u3gjrhmk8s4xlv6kdc6xzhtv0x7px0chuv7smu5n36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZnFMTnd6Ukp6ZFIxNW9l
            cVVzWlpZRGZHT0ZKQ0tVRFJxZUZ3RWsvbkE4CjVHZGVjbWVYWWlRT3Q1WHpJMFRP
            bWNUbzJDc0drTTJKVVkzeTE1bXdzUkEKLS0tIG54SU43TUhnRmhTNTVGN005U0xE
            QWFscWJnYkFZeUdvUzlDdnkvMFhVbDQK0YTsYsAKu11DU8VR6PXeabfltIgGKWXB
            HErIByKrqj/giBTT4h1sjoa6gD5qcwlthbpQaAQ0JsHeN2gmSzfngQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-29T06:45:41Z"
    mac: ENC[AES256_GCM,data:iLN4Yw+90JfFcCm1NZsWL25iU3+908lVSs375cFZTDqc3Ku+0ozotAiRGNenLCiok1NWWhn9mYmq5YmVTMuwGTb+EoBsd/rUKkTUyZZB814VSNFIO6aS/Q/kQVLeKgMqldQYmchCBLeIxDA6R0InWZSreo3DDcdwaptnqdKsm4Y=,iv:sF6K+4067ym0oGXQ+qyWKJnB8huERoaKZFfFPL/1gL8=,tag:ZM3TW/aJDr0kJ5l1UU9OGw==,type:str]
    encrypted_regex: ^(.*password|.*token|.*key|.*secret)$
    version: 3.12.1
