apiVersion: v1
kind: Secret
metadata:
    name: thermo-api-secret
    namespace: thermo
type: Opaque
stringData:
    db_password: ENC[AES256_GCM,data:acKkNzgoTboNXg==,iv:YGAKk+tJgF4Yj+ORTLihLCxlORw1W6LAZSori7I5Fw4=,tag:vidV7NjbEC89I/2iYI+UYg==,type:str]
    influx_token: ENC[AES256_GCM,data:8uuJJZgpNy1P/jMgVKflUw7cC7Y8KX7t1Nk+7/y4bo3VUic0jh1HYUsXMrF3MEa0saYta6PyCGyFFbKf/561wQ==,iv:q51LMB1+Z/oEL/evrxNrAH4pka3hJTdzVQ8428ZPrlk=,tag:mw/0CtTd+bwz1TJaxRRZvg==,type:str]
    api_token: ENC[AES256_GCM,data:4GoaQqJwpO500IyLtzgM7iDT0fk=,iv:FzhiJOj/9A+n0aDvA3ql6EK/b55TdgSK4FkCfgADb/k=,tag:JAPJoXdZOS+3i6tlACobig==,type:str]
sops:
    age:
        - recipient: age17mu4gj9g8yjl68s9u3gjrhmk8s4xlv6kdc6xzhtv0x7px0chuv7smu5n36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ0xMbWtscUZNRGc2RzdC
            R1lqb3dsajBiK0k1Yi8zdTZ6MmNrcEJyUWhVCllqeXJPL2R0aW1FbU9oTC9JS0Q2
            OHRGVFh1RW45L3laWGdxeXh6QTM1dGMKLS0tIHUvRVFCUjJUMktYdS9CZWNzNUxm
            cmFlR3ZwRG5CY1Y5VFpLVC9hM29UMTQKNqBxgtAKKYdqp1Qj3cRsQjm0SWJbz+Ud
            C50c7WGyryvzSnHF7uryr4q3thzJoFWSp871qSXFTAdIx4kLZW+gXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-28T19:55:47Z"
    mac: ENC[AES256_GCM,data:UIT6Aa/cWYntyyfpV0ILcUmSSWdjSuZKj1SxViNvvDvZVajoC5Ci68KMs2ajeiLiPndKKD0V0nH36ir9DlIlZJQ+R3+QvcwolPqhuRAQDhXmmKJo/8kpg8Dop3ufbnTf6xICWb0VpE3HC6La2oQFSrcQA7GA+IiUpDz2J7ByAc0=,iv:1U9nRwNEAWTvWLty6op8BN5EIRunmIYMXckpNTpORkQ=,tag:JPaHgmWkMoYDBjAxGCInvw==,type:str]
    encrypted_regex: ^(.*password|.*token|.*key|.*secret)$
    version: 3.12.1
