apiVersion: v1
kind: Secret
metadata:
  name: thermo-api-secret
  namespace: thermo
type: Opaque
stringData:
  DB_PASSWORD: "sem_heslo_do_mariadb"
  INFLUX_TOKEN: "sem_influxdb_token"
  API_TOKEN: "sem_vygenerovat_nahodny_retezec"