apiVersion: v1
kind: Secret
metadata:
    name: thermo-api-secret
    namespace: thermo
type: Opaque
stringData:
    db_password: ENC[AES256_GCM,data:qJXOnF44v5r0PA==,iv:79JD+z7LOE7LgpksjXixa/uY+K1vU3G/o1pweVBmzGA=,tag:J0g8WC0BHmVbG0GTVWnhyg==,type:str]
    influx_token: ENC[AES256_GCM,data:J0UIQRyqk/K3SZBZ1jtwpVRhDmtZ1NelhtLBS5SosZ/dULa9fPKeZkhiIBo=,iv:613tgcFKTnR/iDel1Aon+2ghwSU7yHHFHhgfImT54WI=,tag:1HpE8NNfzhMPlN2tgnGeTA==,type:str]
    api_token: ENC[AES256_GCM,data:uHANRJm84QzbYh5m30wK78m2K6Y=,iv:oEShm4RUrSdlfpff9Wg1TtjKXcQR3npvpiNFsCaevEs=,tag:FCF18LFrukneoCqtiSETcQ==,type:str]
sops:
    age:
        - recipient: age17mu4gj9g8yjl68s9u3gjrhmk8s4xlv6kdc6xzhtv0x7px0chuv7smu5n36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSE45ZGFqTHJqTHB5dlg3
            WWdaRDhnS3lKOWFsSlFMUU9JV0JkUHZCa2w0Ckc1NU9RV2M1SitNcEt2UW50U1ZD
            THBnRDlVeUpoL0g1dkIzOXRpb1FtMDgKLS0tIEo3YzA1SXVheGNqRStjZXRLZVRx
            dFErNTdpOS9lOVdBWDQrOUp6NXpTZG8KFu2jzv8+A9X5nuGxclJsKs8hFOKCCnaO
            Pic/pnApg+4zeS8Rzs4pinJYSqfzG4y1A4xI3g0xA0wR5SxF4+KvOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T14:30:39Z"
    mac: ENC[AES256_GCM,data:DcoDzgLLu1yiNuv0EHB9kg9UN8vsJZ7vlP3R0VIZyfPs7FYR/A6W9EL6fY2ZnIX0nbPmpGbHyiuAm/uHZJL7hE4r47oUz2ZPssy1NjtJdOWb44/3/f2Akf/MR6aJcis5CbGoHzevf/yop67LESCM4NkLJLd/PYrlEzu+GYaRO0Y=,iv:OV3jP/R0rcfngXMCriTlvtWHZb+tbpsdBCx77zAJ+18=,tag:8sdYWBifSFldndRqfPE2IQ==,type:str]
    encrypted_regex: ^(.*password|.*token|.*key|.*secret)$
    version: 3.12.1
