name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'thermo-api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./thermo-api
          push: true
          tags: |
            ghcr.io/proky7/thermo-api:latest
            ghcr.io/proky7/thermo-api:${{ github.sha }}